"""Curated May 2026 vision model options for OpenRouter.

Verified from OpenRouter model pages. This catalog intentionally includes only
2026 releases with image input. Qwen entries are limited to the 3.5+ and 3.6
series, and qwen3.6-max-preview is excluded because it is text-only.
"""

MODEL_OPTIONS = [
    {
        "id": "google/gemini-3-flash-preview",
        "label": "Gemini 3 Flash Preview",
        "description": "2026 Gemini vision workhorse with image, video, audio, PDF input, 1.05M context, and configurable reasoning.",
        "parameters": "undisclosed",
        "context": "1.05M",
        "pricing": {"input_per_m": 0.50, "output_per_m": 3.00},
        "modalities": ["image", "video", "audio", "pdf"],
        "released": "2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "google/gemini-3.1-pro-preview",
        "label": "Gemini 3.1 Pro Preview",
        "description": "Google frontier multimodal model with image, video, audio, PDF input and 1.05M context.",
        "parameters": "undisclosed",
        "context": "1.05M",
        "pricing": {"input_per_m": 2.00, "output_per_m": 12.00},
        "modalities": ["image", "video", "audio", "pdf"],
        "released": "Apr 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "anthropic/claude-sonnet-4.6",
        "label": "Claude Sonnet 4.6",
        "description": "Anthropic mid-range 2026 vision model for coding, agents, computer use, and document workflows.",
        "parameters": "undisclosed",
        "context": "1M",
        "pricing": {"input_per_m": 3.00, "output_per_m": 15.00},
        "modalities": ["image", "pdf"],
        "released": "2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "anthropic/claude-opus-4.7",
        "label": "Claude Opus 4.7",
        "description": "Anthropic frontier coding and tool-use model with stronger vision for dense documents and UI screenshots.",
        "parameters": "undisclosed",
        "context": "1M",
        "pricing": {"input_per_m": 5.00, "output_per_m": 25.00},
        "modalities": ["image", "pdf"],
        "released": "Apr 15 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "openai/gpt-5.4",
        "label": "GPT-5.4",
        "description": "Unified Codex and GPT model for vision, reasoning, and computer-use agent tasks.",
        "parameters": "undisclosed",
        "context": "1.05M",
        "pricing": {"input_per_m": 2.50, "output_per_m": 15.00},
        "modalities": ["image"],
        "released": "Mar 5 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "openai/gpt-5.5",
        "label": "GPT-5.5",
        "description": "Stronger GPT-5.5 reasoning and agentic workflow model with configurable effort and image input.",
        "parameters": "undisclosed",
        "context": "1.05M",
        "pricing": {"input_per_m": 5.00, "output_per_m": 30.00},
        "modalities": ["image"],
        "released": "Apr 24 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "openai/gpt-5.5-pro",
        "label": "GPT-5.5 Pro",
        "description": "High-accuracy GPT-5.5 variant for deep reasoning and high-stakes vision workloads.",
        "parameters": "undisclosed",
        "context": "1.05M",
        "pricing": {"input_per_m": 30.00, "output_per_m": 180.00},
        "modalities": ["image"],
        "released": "Apr 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "x-ai/grok-4.1-fast",
        "label": "Grok 4.1 Fast",
        "description": "Low-cost 2M-context xAI vision model for agentic tool calling, support, and deep research.",
        "parameters": "undisclosed",
        "context": "2M",
        "pricing": {"input_per_m": 0.20, "output_per_m": 0.50},
        "modalities": ["image"],
        "released": "2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "qwen/qwen3.5-397b-a17b",
        "label": "Qwen3.5 397B-A17B",
        "description": "Open-weight Qwen3.5 flagship with image and video input, GUI interaction strength, and Apache 2.0 weights.",
        "parameters": "397B",
        "context": "262K",
        "pricing": {"input_per_m": 0.39, "output_per_m": 2.34},
        "modalities": ["image", "video"],
        "released": "Feb 16 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "qwen/qwen3.5-plus-20260420",
        "label": "Qwen3.5 Plus 20260420",
        "description": "Latest Qwen3.5 Plus checkpoint with 1M context and image/video input.",
        "parameters": "undisclosed",
        "context": "1M",
        "pricing": {"input_per_m": 0.40, "output_per_m": 2.40},
        "modalities": ["image", "video"],
        "released": "Apr 27 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "qwen/qwen3.5-122b-a10b",
        "label": "Qwen3.5 122B-A10B",
        "description": "Practical mid-tier Qwen3.5 vision model with image/video input and 262K context.",
        "parameters": "122B",
        "context": "262K",
        "pricing": {"input_per_m": 0.26, "output_per_m": 2.08},
        "modalities": ["image", "video"],
        "released": "Feb 25 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "qwen/qwen3.6-plus",
        "label": "Qwen3.6 Plus",
        "description": "Most capable Qwen3.6 vision model with strong agentic coding, front-end, and repository workflows.",
        "parameters": "undisclosed",
        "context": "1M",
        "pricing": {"input_per_m": 0.325, "output_per_m": 1.95},
        "modalities": ["image", "video"],
        "released": "Apr 2 2026",
        "vision": True,
        "source": "OpenRouter",
    },
    {
        "id": "qwen/qwen3.6-flash",
        "label": "Qwen3.6 Flash",
        "description": "Newest fast Qwen3.6 vision model with image/video input, 1M context, and prompt caching support.",
        "parameters": "undisclosed",
        "context": "1M",
        "pricing": {"input_per_m": 0.25, "output_per_m": 1.50},
        "modalities": ["image", "video"],
        "released": "Apr 27 2026",
        "vision": True,
        "source": "OpenRouter",
    },
]


def get_model_options():
    return MODEL_OPTIONS
